/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testsuite;

import java.util.*;

public class Customer {
    private Set<String> preferences;  // set of preferences
    private List<String> advertisements;   // list of received advertisements
    private int maxAdvs;     // maximum number of ads a customer can have

    public Customer(Set<String> preferences, List<String> advertisements, int maxAdvs) {
        this.preferences = preferences;
        this.advertisements = advertisements;
        this.maxAdvs = maxAdvs;
    }
  
     // Getters and setters for all fields
    public Set<String> getPreferences() {
        return new HashSet<>(this.preferences);  // Return a copy to prevent direct modification
    }

    public List<String> getAdvertisements() {
        return new ArrayList<>(this.advertisements);  // Return a copy to prevent direct modification
    }

    public int getMaxAdvs() {
        return this.maxAdvs;
    }

    public void setPreferences(Set<String> preferences) {
        this.preferences = new HashSet<>(preferences);
    }

    public void setAdvertisements(List<String> advertisements) {
        this.advertisements = new ArrayList<>(advertisements);
    }

    public void setMaxAdvs(int maxAdvs) {
        this.maxAdvs = maxAdvs;
    }

    public boolean addAdvertisement(String adv) {
        if (this.advertisements.size() < this.maxAdvs) {
            this.advertisements.add(adv);
            return true;
        } else {
            return false;
        }
    }

    public List<String> readAdvertisements(int n) {
        int count = Math.min(n, this.advertisements.size());  // It will be equal to n if n is less than or equal size of list
        
        List<String> lastNAdv = new ArrayList<>(this.advertisements.subList(this.advertisements.size() - count, this.advertisements.size()));
      
        // Print the advertisement
        for (String adv : lastNAdv) {
            System.out.println(adv);
        }
        
        // Delete from list
        this.advertisements.removeAll(lastNAdv);
    
        return lastNAdv;  // Return deleted advertisements
    }

    
    
}

