/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testsuite;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Field;
import java.util.*;

import org.junit.Before;

public class CustomerTest {
    @Before
    public void initialize(){
        Set<String> preferences = new HashSet<>(Arrays.asList("Sports", "Technology"));
        List<String> advertisements = new ArrayList<>(Arrays.asList("Ad1", "Ad2"));
        int maxAdvs = 5;
        Customer customer = new Customer(preferences, advertisements, maxAdvs);
    }
    
    @Test
    public void testCustomerFields() {
        Set<String> expectedFields = new HashSet<>(Arrays.asList("preferences", "advertisements", "maxAdvs"));
        Set<String> actualFields = getClassFields(Customer.class);
        assertEquals(expectedFields, actualFields);
    }
    
    // Helper method to get the names of fields in a class
    private Set<String> getClassFields(Class<?> clazz) {
        Set<String> fieldNames = new HashSet<>();
        Field[] fields = clazz.getDeclaredFields();
        for (Field field : fields) {
            fieldNames.add(field.getName());
        }
        return fieldNames;
    }

}
